add_newline = false

format = """
$directory$git_branch$git_status$python$rust$nodejs$character
"""

# ------------------------------------------------------------
# directory
# ------------------------------------------------------------

[directory]
style = "bold #bbbbbb"
truncation_length = 3
truncate_to_repo = true
read_only = " 󰌾"

# ------------------------------------------------------------
# git
# ------------------------------------------------------------

[git_branch]
symbol = " "
style = "#aaaaaa"

[git_status]
style = "#888888"

# red when something is wrong
conflicted = "[✖](bold red)"
deleted = "[✘](red)"
modified = "[●](red)"

# ------------------------------------------------------------
# languages
# ------------------------------------------------------------

[python]
symbol = " "
style = "#aaaaaa"

[rust]
symbol = "󱘗 "
style = "#aaaaaa"

[nodejs]
symbol = " "
style = "#aaaaaa"

# ------------------------------------------------------------
# errors
# ------------------------------------------------------------

[status]
symbol = " "
style = "bold red"

# ------------------------------------------------------------
# prompt character
# ------------------------------------------------------------

[character]
success_symbol = "[›](bold #dddddd)"
error_symbol = "[›](bold red)"